### ISSUE TITLE
Doesn't create maildir anymore

### ISSUE THREAD

**Issue by schwindelbub** [opensolutions/ViMbAdmin#205]
Hi,

the ViMbAdmin doesn't create maildirs anymore. It creates the datebase entry but nothing on the filesystem. If i try to delete it, it doesn't delete the database entry. So if i try to create the same mailbox again, an error message is shown.

A few weeks ago everything works fine. I created some mailboxes. I have no idea, what changed on the system.

Has anybody an idea? Or an hint for me?

Debian 8
PHP 5.6

Thanks and best regards
Schwindelbub

**Comment by PhrozenByte** [comment]
ViMbAdmin never created directories on the filesystem, this is up to your MDA/LDA. ViMbAdmin just tells your MDA/LDA *where* to create the directories. What did you delete (the filesystem folder or the database entry?) and what exact error message is shown?

**Comment by barryo** [comment]
Hi @schwindelbub - @PhrozenByte is correct, ViMbAdmin never created any filesystem entries (this is because we never assumed ViMbAdmin and the mail server are necessarily on the same server).

I'm closing this as it's neither a bug nor a feature request but feel free to continue the conversation (or, more appropriately, move it to the mailing list).
