### ISSUE TITLE
Add mailbox from cli

### ISSUE THREAD

**Issue by endelwar** [opensolutions/ViMbAdmin#212]
I can't find any hint about adding a new mailbox from command line or in an automated way.
I've a long csv file with email and password and I would like to automate this task.

**Comment by gibzer** [comment]
I wrote Perl scripts to automate some actions:
- create mailboxes;
- create aliases;
- delete aliases;
- change passwords.

They need no any Perl dependencies, but doveadm for creating passwords with selected password scheme (because ViMbAdmin in standard tutorial uses Dovecot, it's assumed as installed). They do what is expected, except adding a record to log table. Adjust database settings in scripts (plus mail paths in "create mailbox" script). Read input format in the beginning of script (field delimiter is tabulation).

Usage: ./script file_with_data
or
echo "data" | ./script

Hope it will help.

**Comment by endelwar** [comment]
@gibzer great scripts, I've found them very useful!
You should create a PR with them

**Comment by gibzer** [comment]
Created repository for scripts: https://github.com/gibzer/vimbadmin-cli

**Comment by extremeshok** [comment]
Hi

The repo should be called vimbadmin-perl.

Since they do not use actual shell nor the native vimbadmin code.

One would assume the cli would be using php and not perl

Thanks


_________________ eXtremeSHOK.com _________________

**Comment by gibzer** [comment]
Done.
https://github.com/gibzer/vimbadmin-perl

**Comment by endelwar** [comment]
I don't agree with @extremeshok, they are Command Line Interface to ViMbAdmin, php has nothing to do with this.
If @gibzer wants to rename the project ti should be vimbadmin-tools or something like that...

**Comment by barryo** [comment]
Added to: https://github.com/opensolutions/ViMbAdmin/wiki/Third-Party-Applications
